---
version: '3'

services:
  teamcity:
    image: 
      jetbrains/teamcity-server:latest
    hostname:
      teamcity
    container_name:
      teamcity
    ports:
     - 8112:8111
    environment:
      - TEAMCITY_SERVER_MEM_OPTS="-Xmx750m"
    volumes:
      - ./server_data:/data/teamcity_server/datadir
      - ./server_logs:/opt/teamcity/logs
      - ./server_root:/root
  
  teamcity-agent:
    image: 
      jetbrains/teamcity-agent:latest
    hostname:
      teamcity-agent
    container_name:
      teamcity-agent
    depends_on:
      - teamcity
    environment:
      - SERVER_URL=http://teamcity:8111
      - AGENT_NAME=docker_agent
    volumes:
      - ./agent_conf:/data/teamcity_agent/conf
      - ./agent_root:/root